#!/bin/sh
chosen=$(printf "Nord\nEverforest\nParadise\nFrost\nRose Pine Dawn\nTokyo Night Storm\nGruvbox Material\nCatppuccin\nAshes\nPywal (Random)\n" | rofi -dmenu -p "" -i)

case "$chosen" in
  "Nord") nord ;;
  "Everforest") everforest ;;
  "Paradise") paradise ;;
  "Frost") frost ;;
  "Rose Pine Dawn") rose-pine-dawn ;;
  "Tokyo Night Storm") tokyo-night-storm ;;
  "Gruvbox Material") gruvbox-mat ;;
  "Catppuccin") catppuccin ;;
  "Ashes" ) ashes ;;
  "Pywal (Random)" ) pywal ;;
  *) exit 1 ;;
esac
