#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom  &
$HOME/.config/polybar/launch.sh
bspc monitor -d I II III IV V

bspc config border_width         3
bspc config window_gap           10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true 

# Set the border colors.
bspc config normal_border_color 
bspc config active_border_color 
bspc config focused_border_color "#88C0D0"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"
xset -dpms s off

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a firefox desktop='^4'
bspc rule -a Thunar desktop='^5'
#bspc rule -a discord desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


