#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom  &
bspc monitor -d I II III IV V

bspc config border_width         0
bspc config window_gap           10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true 
bspc config top_padding          60 

$HOME/.config/polybar/launch.sh
# Set the border colors.
bspc config normal_border_color   
bspc config active_border_color 
bspc config focused_border_color "#95aec7"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"
xset -dpms s off

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

