#!/bin/sh
chosen=$(printf "Nord\nEverforest\nParadise\nGruvbox Material\nFrost\n" | rofi -dmenu -p "" -i -theme-str '@import "theme-switcher.rasi"')

case "$chosen" in
  "Nord") nord ;;
  "Everforest") everforest ;;
  "Paradise") paradise ;;
  "Gruvbox Material") gruvbox-mat ;;
  "Frost") frost ;;
  *) exit 1 ;;
esac
